<?php

return [
    'nav_dashboard' => 'Dashboard',
    'nav_login' => 'Log in',
    'nav_register' => 'Register',

    'hero_title' => 'Student Payment & Attendance Management System',
    'hero_description' => 'This is a placeholder for the name soon to be added.',

    'section_1_title' => 'What This App Does',
    'section_1_body' => 'This application is a Student Payment & Attendance Management System designed to streamline tuition payment tracking and attendance monitoring. In addition to managing payment records, the system allows teachers to record attendance and enables students and parents to view attendance history. Parents can also submit absence reasons, such as illness or other circumstances. This integrated system helps improve communication, accuracy, and overall management within the institution.',
    'section_2_title' => 'How To Start',
    'section_2_body' => 'Users can begin by registering an account as a parent through the sign-up page. After logging in, users can access their dashboard to view attendance records, including any absences and their details. Parents and students can also monitor outstanding tuition fees and complete payments directly through the application. The system provides a simple and convenient way to stay updated on attendance and manage payments in one place.',
    'section_3_title' => 'About System',
    'section_3_body' => 'The system employs a centralized account management strategy where Student and Parent accounts are strictly generated by the Administrator. To ensure financial security and data integrity, each student profile must be linked to a verified Parent/Guardian email address. This connection is crucial for the billing cycle; once linked, parents receive access to their child\'s specific tuition dashboard, allowing them to upload payment proofs and track tuition fees. This Admin-First registration approach prevents unauthorized account creation and ensures that every payment is accurately reconciled with the correct student record.',
    'person_title' => 'About This Person',
    'person_body' => 'The institution is led by Jane Doe, a dedicated educator and entrepreneur with a profound vision for modernizing supplementary education. With years of experience in academic management, the owner established this tuition center to provide high-quality, structured learning for students. Her commitment to excellence is the driving force behind this digital transformation.',

    'map_title' => 'Location',
    'map_body' => 'This map shows the location of the school or tutoring center where the system is used.',
];
